modLoader="javafml"
loaderVersion="[33,)" 
issueTrackerURL="https://github.com/TeamFelnull/OtyacraftEngine/issues"
logoFile="logo.png" 
license="LGPL v3"
[[mods]]
modId="otyacraftengine"
version="${file.jarVersion}" 
displayName="Otyacraft Engine"
updateJSONURL="https://raw.githubusercontent.com/TeamFelnull/OtyacraftEngine/master/update_check.json" 
displayURL="https://www.curseforge.com/minecraft/mc-mods/otyacraft-engine" 
credits="TeamFelNull"
authors="MORIMORI0317" 
description="Thank you for downloading!\nThis mod is my mod integration library."
